FROM ubuntu:20.04

RUN apt update

RUN apt-get install build-essential libssl-dev git unzip -y
RUN git clone https://github.com/wg/wrk.git wrk \
    && cd wrk \
    && make \
    && cp wrk /usr/local/bin