FROM golang:1.17-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /go-server

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /go-server /go-server

EXPOSE 12345

USER nonroot:nonroot

ENTRYPOINT ["/go-server"]