
alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
pushgateway:
  enabled: false
nodeExporter:
  enabled: false

server:
  service:
    servicePort: 9090
  persistentVolume:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000