
alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
pushgateway:
  enabled: false
nodeExporter:
  enabled: false

server:
  global:
    scrape_interval: 5s
  service:
    servicePort: 9090
  persistentVolume:
    enabled: false