apiVersion: apps/v1
kind: Deployment
metadata:
  name: az1-client-node1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-node1
      region: az1
  template:
    metadata:
      labels:
        app: client-node1
        region: az1
    spec:
      containers:
        - image: docker.io/mkyo114/az1-client-linux:v2
          name: client-node1
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      nodeSelector:
        kubernetes.io/hostname: node1-client-az1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az1-client-node1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-node1
      region: az1
  template:
    metadata:
      labels:
        app: client-node1
        region: az1
    spec:
      containers:
        - image: docker.io/mkyo114/az1-client-linux:v2
          name: client-node1
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      nodeSelector:
        kubernetes.io/hostname: node3-client-az1