apiVersion: apps/v1
kind: Deployment
metadata:
  name: az1-client-node1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-node1
      region: az1
  template:
    metadata:
      labels:
        app: client-node1
        region: az1
      annotations:
        sidecar.istio.io/proxyCPULimit: "10000m"
        proxy.istio.io/config: 'concurrency: 10'
    spec:
      containers:
        - image: docker.io/mkyo114/az1-client-linux:v2
          name: client-node1
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          resources:
            requests:
              cpu: "4000m"
              memory: "2048Mi"
            limits:
              cpu: "4000m"
              memory: "2048Mi"
      nodeSelector:
        kubernetes.io/hostname: node1-client-az1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az1-client-node3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-node3
      region: az1
  template:
    metadata:
      labels:
        app: client-node3
        region: az1
      annotations:
        sidecar.istio.io/proxyCPULimit: "4000m"
        proxy.istio.io/config: 'concurrency: 4'
    spec:
      containers:
        - image: docker.io/mkyo114/az1-client-linux:v2
          name: client-node3
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          resources:
            requests:
              cpu: "1000m"
              memory: "1024Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
      nodeSelector:
        kubernetes.io/hostname: node3-client-az1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az2-client-node4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-node4
      region: az2
  template:
    metadata:
      labels:
        app: client-node4
        region: az2
      annotations:
        sidecar.istio.io/proxyCPULimit: "4000m"
        proxy.istio.io/config: 'concurrency: 4'
    spec:
      containers:
        - image: docker.io/mkyo114/az1-client-linux:v2
          name: client-node4
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          resources:
            requests:
              cpu: "1000m"
              memory: "1024Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
      nodeSelector:
        kubernetes.io/hostname: node4-client-az2
