apiVersion: v1
data:
  watcher.sh: |-
    #!/bin/sh

    while true;
    do
       sleep 15;
       kubectl top pods --selector='region=$1,app=$2' >> aaa.txt
    done;
kind: ConfigMap
metadata:
  name: watcher-script