apiVersion: apps/v1
kind: Deployment
metadata:
  name: az1-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      region: az1
  template:
    metadata:
      labels:
        app: server
        region: az1
      annotations:
        sidecar.istio.io/proxyCPULimit: "10000m"
        proxy.istio.io/config: 'concurrency: 10'
    spec:
      containers:
        - image: mkyo114/az1-nginx:v3
          name: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "4000m"
              memory: "2048Mi"
            limits:
              cpu: "4000m"
              memory: "2048Mi"
      nodeSelector:
        kubernetes.io/hostname: node2-server-az1
