apiVersion: apps/v1
kind: Deployment
metadata:
  name: az2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      region: az2
  template:
    metadata:
      labels:
        app: server
        region: az2
    spec:
      containers:
        - image: docker.io/mkyo114/az2-serve-linux:v4
          name: go-server
          ports:
            - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: node5-server-az2
