apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: watcher
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["get", "patch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: watcher
subjects:
- kind: ServiceAccount
  name: watcher