apiVersion: apps/v1
kind: Deployment
metadata:
  name: az1-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
      region: az1
  template:
    metadata:
      labels:
        app: server
        region: az1
      annotations:
        sidecar.istio.io/proxyCPULimit: "4000m"
        proxy.istio.io/config: 'concurrency: 4'
    spec:
      containers:
        - image: mkyo114/az1-nginx:v3
          name: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "450m"
              memory: "1024Mi"
            limits:
              cpu: "450m"
              memory: "1024Mi"
      nodeSelector:
        kind: server
