apiVersion: apps/v1
kind: Deployment
metadata:
  name: az2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      region: az2
  template:
    metadata:
      labels:
        app: server
        region: az2
      annotations:
        sidecar.istio.io/proxyCPULimit: "4000m"
        proxy.istio.io/config: 'concurrency: 4'
    spec:
      containers:
        - image: mkyo114/az2-nginx:v3
          name: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
      nodeSelector:
        kubernetes.io/hostname: node5-server-az2
