apiVersion: apps/v1
kind: Deployment
metadata:
  name: az2-server
  annotations:
    sidecar.istio.io/proxyCPULimit: "4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      region: az2
  template:
    metadata:
      labels:
        app: server
        region: az2
    spec:
      containers:
        - image: mkyo114/az2-nginx:v3
          name: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "300m"
              memory: "1024Mi"
            limits:
              cpu: "300m"
              memory: "1024Mi"
      nodeSelector:
        kubernetes.io/hostname: node5-server-az2
