apiVersion: apps/v1
kind: Deployment
metadata:
  name: az1-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
      region: az1
  template:
    metadata:
      labels:
        app: watcher
        region: az1
    spec:
      serviceAccountName: watcher
      containers:
      - image: lachlanevenson/k8s-kubectl:v1.21
        name: watcher
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - mountPath: /home
            name: watcher-script
      volumes:
        - name: watcher-script
          configMap:
            name: watcher-script
      nodeSelector:
        kubernetes.io/hostname: node2-server-az1