prometheus:
  url: http://prometheus-server.monitoring.svc.cluster.local
  port: 9090

rules:
  custom:
  - seriesQuery: 'istio_request_duration_milliseconds_bucket'
    resources:
      overrides:
        app:
          resource: "client-node1"
        reporter:
          resource: "source"
        destination_workload:
          resource: "az1-server"
    name:
      as: "client1-to-server1-p80"
    metricsQuery:
      "histogram_quantile(0.8,sum(irate(<<.Series>>{<<.LabelMatchers>>}[30s]))by (destination_canonical_service,destination_workload_namespace,source_canonical_service,source_workload_namespace,le))"




