apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server
spec:
  hosts:
    - server
  http:
   - route:
     - destination:
         host: server
         subset: az1
       weight: 0
     - destination:
         host: server
         subset: az2
       weight: 100